### ISSUE TITLE
Better example code

### ISSUE THREAD

**Issue by lfarah** [behrad-kzm/BEKCurveTabbar#1]
Your library seems amazing, but it would be helpful to have more code examples since there are a lot of developers who do not use the Interface Builder. You can use [ESTabBarController](https://github.com/ezescaruli/ESTabBarController) as an example.

**Comment by behrad-kzm** [comment]
Thanks for the response.
I added some new files and modified readme file and added better example.
check it out its super easy to use.

**Comment by lfarah** [comment]
Awesome job!
