### ISSUE TITLE
Configurable rounded corners individually !

### ISSUE THREAD

**Issue by wonder2011** [behrad-kzm/BEKCurveTabbar#3]
Hi there, awesome component. I will use this everytime. But i have a problem, i need corner radius of this Tabbar to be configurable, like IBAnimatable did: https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/APIs.md#cornerdesignable

For example, i need to implement a tabbar rounded topLeft and topRight but squared in bottomLeft and bottomRight. Is this possible @behrad-kzm ??

I exactly need to make this tabbar: https://www.cubacitas.app/wp-content/uploads/2019/09/mobil3.png, but this bar only have one property for all borders...

**Comment by behrad-kzm** [comment]
Hi there, 
I've just added two new parameters of 'topCornerRadius' and 'bottomCornerRadius' to the Tabbar and also updated the ViewModels.
Cheers!
